version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container1
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth
    environment:
      - SECRET=FJDVKVNKLSDNVLKSNVLnvdfsnkvlksdMKVDMCV43254
      - PORT=3001
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=strong-password
      - DATABASE_USERNAME=user-name
      - DATABASE_NAME=postgres
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - .:/src
    restart: unless-stopped
    network_mode: host
    command: npm run start:dev

volumes:
  local_pgdata:
  pgadmin-data:
  cache:
    driver: local
